let industries = {
  "Graphic Designer": {
    name: "Graphic Designer",
    file: "graphic.png",
    svg: "graphic-vector.svg",
    color: "#6F39DF",
    text: "graphic-text.png",
    textSvg: "graphic-text-vector.svg",
  },
  "UX/UI Designer": {
    name: "UX/UI Designer",
    file: "uxui.png",
    svg: "uxui-vector.svg",
    // file: "UXUI.png",
    color: "#5E96FF",
    text: "uxui-text.png",
    textSvg: "uxui-text-vector.svg",
  },
  Illustrator: {
    name: "Illustrator",
    file: "illustrator.png",
    svg: "illustrator-vector.svg",
    color: "#F2AE49",
    text: "illustrator-text.png",
    textSvg: "illustrator-text-vector.svg",
  },
  "Game Designer": {
    name: "Game Designer",
    file: "game.png",
    svg: "game-vector.svg",
    // file: "gameDesigner.png",
    color: "#4ED07A",
    text: "game-text.png",
    textSvg: "game-text-vector.svg",
  },
  "AI Designer": {
    name: "AI Designer",
    file: "ai.png",
    svg: "ai-vector.svg",
    color: "#E25757",
    text: "ai-text.png",
    textSvg: "ai-text-vector.svg",
  },
  "Packaging Designer": {
    name: "Packaging Designer",
    file: "packaging.png",
    svg: "packaging-vector.svg",
    color: "#A9926F",
    text: "packaging-text.png",
    textSvg: "packaging-text-vector.svg",
  },
  "AR/VR Designer": {
    name: "AR/VR Designer",
    file: "arvr.png",
    svg: "arvr-vector.svg",
    color: "#39D8D8",
    text: "arvr-text.png",
    textSvg: "arvr-text-vector.svg",
  },
};
